import type { LabProject } from '@/lib/types'

export const labs: LabProject[] = [
  {
    slug: 'focus-tracker',
    name: 'focus-tracker',
    type: 'dir',
    description: 'Smart Pomodoro timer with real-time distraction detection and analytics',
    longDescription: 'Built a production-ready focus tracking system with tab-switch detection, gamification (XP/levels/badges), session analytics with weekly charts, and smart reminders via Notifications API.',
    tech: ['React', 'TypeScript', 'Vite', 'Recharts', 'localStorage'],
    status: 'active',
    date: '2026-04',
    github: '#',
  },
  {
    slug: 'distributed-cache-layer',
    name: 'distributed-cache-layer',
    type: 'dir',
    description: 'Redis-based caching with TTL management, invalidation strategies, and cache warming',
    tech: ['Java', 'Spring Boot', 'Redis', 'Docker'],
    status: 'active',
    date: '2025-11',
  },
  {
    slug: 'kafka-consumer-patterns',
    name: 'kafka-consumer-patterns.md',
    type: 'file',
    description: 'Patterns for reliable async message processing — retries, DLQ, exactly-once semantics',
    tech: ['Kafka', 'Java', 'Spring Boot'],
    status: 'archived',
    date: '2024-08',
  },
  {
    slug: 'api-rate-limiter',
    name: 'api-rate-limiter',
    type: 'dir',
    description: 'Token bucket + sliding window rate limiter for API gateway protection at scale',
    tech: ['Java', 'Redis', 'Spring Boot', 'REST'],
    status: 'active',
    date: '2025-06',
  },
  {
    slug: 'microservices-monitor',
    name: 'microservices-monitor',
    type: 'dir',
    description: 'Service health monitoring with anomaly detection and automated alerting',
    tech: ['Go', 'Prometheus', 'Grafana', 'Docker'],
    status: 'building',
    date: '2026-02',
  },
  {
    slug: 'system-design-notes',
    name: 'system-design-notes.md',
    type: 'file',
    description: 'Personal notes on distributed systems patterns — CAP theorem, consensus, partitioning',
    tech: ['Distributed Systems', 'Architecture'],
    status: 'active',
    date: '2026-03',
  },
]
